version: '3.7'
services:
  node-red:
    build:
      context: ./node-red
    container_name: node-red
    working_dir: /data
    environment:
      - TZ=Asia/Tokyo
      - GCP_API_KEY=${GCP_API_KEY}
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/data:/data
    command: >
      sh -c 'node-red --userDir /data'
